### ISSUE TITLE
Visor position fix when over a fullscreen app

### ISSUE THREAD

**Issue by nixpulvis** [binaryage/totalterminal#104]
It would be nice if the visor slid down from the top of the screen when it was over a fullscreen app.

![screen shot 2014-05-14 at 8 36 40 pm](https://cloud.githubusercontent.com/assets/715947/2979218/030fb5e4-dbc9-11e3-9b8f-9b931dd0b941.png)

This looks funky.

**Comment by nixpulvis** [comment]
This is still an issue, is this something that can be fixed easily. I don't know that much about how this app interacts with OS X.

**Comment by darwin** [comment]
FYI, I no longer develop TotalTerminal:
http://totalterminal.binaryage.com/#sip

**Comment by nixpulvis** [comment]
Ah, I'm sorry to hear that. Thanks for the great software.

**Comment by 1-61803** [comment]
[popavo](https://github.com/popavo) smashed this bug years ago, but somehow it never made it to master, I think, since it reappears from 1.4.2 on. Fortunately, the osax is still available from his dropbox, [here](https://dl.dropboxusercontent.com/u/1726078/TotalTerminal.zip). I just downgraded from 1.5.4 to 1.3 to retest it and regain paste on right click.
