### ISSUE TITLE
when TotalTerminal is opened, there's always a second terminal window

### ISSUE THREAD

**Issue by localheinz** [binaryage/totalterminal#43]
Affects TotalTerminal 1.2.2 on OSX 10.8.

**Comment by darwin** [comment]
this is by design, I don't force closing existing windows anymore: b4d2b4a9c650ac19295f3c506e7601d41f23ae13

`defaults write com.apple.Terminal TotalTerminalCloseWindowsOnStart -bool YES`

**Comment by localheinz** [comment]
Thanks a lot, @darwin. I'll close this issue then, as it works for me.

**Comment by darwin** [comment]
We improved this in v1.4.2+. We auto-close all windows if Terminal process is very young. This covers both cases nicely. When you launch Terminal.app and immediately inject TotalTerminal, then windows will be auto-closed. In other case we don't touch them.

**Comment by clrunlc** [comment]
Could you just do nothing? Neither open extra Terminal windows, nor close existing Terminal windows?
I have to be stick with TotalTerminal 1.3.
`defaults write com.apple.Terminal TotalTerminalCloseWindowsOnStart -bool YES` didn't work for me, whatever it's turned on or off

**Comment by darwin** [comment]
In 1.4.5 I have introduced `defaults write com.apple.Terminal TotalTerminalDoNotTouchWindowsOnStart -bool YES`. This will perform no action. 

Version 1.4.5 should get out sometime this week with other minor fixes.

**Comment by ghost** [comment]
I'm having this issue with latest version (1.4.5) and using TotalTerminalCloseWindowsOnStart doesn't seem to work anymore. Any hint?

P.S.: I'm using Mavericks

**Comment by darwin** [comment]
Hmm, it should work. This is the actual code in 1.4.5:
https://gist.github.com/darwin/5297433285275dc529cc#file-boot-mm-L6

**Comment by ghost** [comment]
Uhm nope, just tried again. It doesn't work even setting explicitely TotalTerminalDoNotTouchWindowsOnStart to 0.
Here the complete list of my settings from com.apple.Terminal:

```
TotalTerminalCloseWindowsOnStart = 1;
TotalTerminalCopyOnSelect = 1;
TotalTerminalDoNotLaunchCrashWatcher = 1;
TotalTerminalDontCustomizeDockIcon = 1;
TotalTerminalHideDockIcon = 1;
TotalTerminalLoggingDisabled = 1;
TotalTerminalPasteOnRightClick = 1;
TotalTerminalShortcuts =     {
    PinVisor =         {
        KeyCode = 35;
        Modifiers = 1179648;
    };
    ToggleVisor =         {
        KeyCode = 50;
        Modifiers = 262144;
    };
};
TotalTerminalShowStatusItem = 0;
TotalTerminalSuppressTerminalVersionCheck = 1;
TotalTerminalUsePreReleases = 1;
TotalTerminalVisorAnimationSpeed = "0.2668648097826087";
TotalTerminalVisorBackgroundAnimationOpacity = 100;
TotalTerminalVisorExposeFrontmostAndVisibleProperties = 0;
TotalTerminalVisorFullScreen = 0;
TotalTerminalVisorHideOnEscape = 1;
TotalTerminalVisorHotKey2 =     {
    DoubleModifier = 1;
    KeyCode = 0;
    Modifiers = 262144;
};
TotalTerminalVisorHotKey2Enabled = 0;
TotalTerminalVisorHotKey2Mask = 262144;
TotalTerminalVisorOnEverySpace = 1;
TotalTerminalVisorPinned = 0;
TotalTerminalVisorPosition = "Top-Stretch";
TotalTerminalVisorScreen = 0;
TotalTerminalVisorShowOnReopen = 1;
TotalTerminalVisorUseBackgroundAnimation = 0;
TotalTerminalVisorUseFade = 0;
TotalTerminalVisorUseSlide = 1;
TotalTerminalVisorWindowOnHighLevel = 0;
```

**Comment by darwin** [comment]
you should not set it 0, set it to 1 (or yes)

this worked for me on my machine:

```
defaults write com.apple.Terminal TotalTerminalDoNotTouchWindowsOnStart -bool yes
```

**Comment by ghost** [comment]
With both parameters set to 1 it still opens a normal window on login. I want it to close it that's why i set the "do not perform any action" setting to 0 (because I indeed wanted it to perform the action of closing that window)

**Comment by darwin** [comment]
Ah, I'm sorry I pasted a bad setting key in previous comment.

`TotalTerminalCloseWindowsOnStart` should be set and no other

```
defaults delete com.apple.Terminal TotalTerminalDoNotTouchWindowsOnStart
defaults write com.apple.Terminal TotalTerminalCloseWindowsOnStart -bool yes
```

**Comment by ghost** [comment]
Ok but we are back to the beginning it doesn't seem to work anymore :(

**Comment by darwin** [comment]
Execute those two commands and then send me your com.apple.Terminal.plist to support@binaryage.com. I will check it.

**Comment by darwin** [comment]
I just tested your plist on my machine and it works as expected.

When I quit Terminal.app and then launch /Applications/TotalTerminal.app
1) Terminal.app gets launched and opens its window
2) TotalTerminal gets injected in few seconds and closes that window

**Comment by ghost** [comment]
Ok it indeed works after login: manually opening Terminal launches its window and then launching TotalTerminal closes it.
Unfortunately it doesn't happen at login (both after a logout and a reboot). I have TotalTerminal as login item.
I also tried with both the option to hide the window at login checked and unchecked (the little setting in the login items preferences next to the app to automatically launch).

**Comment by darwin** [comment]
Interesting. In theory my windows-closing code could run before Terminal.app creates that window. This could probably happen when Terminal.app is slow launching and TotalTerminal is quick in injecting. This could be your scenario. But still it is unlikely because TotalTerminal waits 2 seconds before trying to manipulate windows, that's why the method is called "delayedBoot".

I'm afraid I won't fix this for you. I have to wait for more people having similar issues.

**Comment by ale275** [comment]
same problem here on mavericks, if opened on login it doesn't close the windows, if opened manually it does

**Comment by mukerjee** [comment]
Same problem here, on Mountain Lion. Having total terminal open on login causes a terminal window to pop-up, but launching it manually does not. 
Even though the terminal window pops up after login, total terminal doesn't actually run, as there's no icon in the status menu nor does it respond to the show visor hotkey. Launching it manually is required.

Edit: this seems to be fixed after upgrading to Mavericks, for me at least.

**Comment by jjrp78** [comment]
o/
one more here. For me it goes:
1. Open TotalTerminal (either at start up or manually)
2. I get a terminal window
3. If I close the window with command-W (i.e. close the window only), next time I open Total terminal it works fine

... however
if in (3) I close the window with command-Q (i.e. quit the app) then when I open TotalTerminal next time I get the window..so kind of back to (1)

Hope that helps to fix the issue

**Comment by loveencounterflow** [comment]
people this is ridiculous. you're doing it wrong. can't be so difficult to just open that window group i had openend and saved by name the last time, no? instead i get those pesky default-styled letterbox windows, and each time i switch on my computer, there's a new one. i then have to hunt across several desktop spaces and click to close; it's like a whack-a-mole game and i don't enjoy it.

darwin, thanks for your hard work and your dedication, and i do have reasons to use totalterminal instead of iterm. but if you're at the point where (1) we have to use the command line to do absolutely basic settings, (2) those settings fail in interesting ways, and (3) you get the names wrong when posting here—chances are naming went wrong and intentions are not clear. 

you're talking versions here, but where can i see the version i'm using right now? not from the preferences or the about window for sure. that's an important one, you always want to know where you're standing when reading a thread like this.

**Comment by darwin** [comment]
@loveencounterflow TT version is in TotalFinder preferences pane at the bottom. 

TotalTerminal might not be suitable for everyone. It is not my goal to support all possible workflows, my goal is to make Terminal enhancement for myself and my workflows. TotalTerminal never supported Window Groups well, I'm sorry.

1) settings discussed in this topic are not basic IMO
2) can you be more specific what setting failed and in what way?
3) what names did I get wrong?

**Comment by loveencounterflow** [comment]
ok so that was fast.

turns out my version is 1.5.3, thanks for pointing that one out to me; i had looked around but was too fast for the small print.

@3 quote: """Ah, I'm sorry I pasted a bad setting key in previous comment. [...] `TotalTerminalDoNotTouchWindowsOnStart` [...] `TotalTerminalCloseWindowsOnStart`"""

@1 i totally find that in any GUI application handling windows is absolutely basic. i don't expect TotalTerminal to support any conceivable workflow, but, look: 

@2 i just set `TotalTerminalCloseWindowsOnStart` to `true`, closed TT, re-opened it, and guess what happened. all my previously opened windows got opened, plus that letterbox window i don't want. then TT proceeded and closed all the windows, leaving me with none. i then swapped that setting to `false`, with no effect. as a tester i can now confirm i don't know what that setting is for. i go Window > Open Window Group > ... to re-open my named group which i do get back, but i still have to do the whack-a-mole thing with that letterbox window.

to be specific, i suggest to (1) re-open all windows in the state they were when TT last got closed, and (2) not to open letterbox windows unless TT is command-tabbed to and has currently no window open (leaving open the question why i get a small-print black-on-white window at all when my settings indicate i like bigger print and white-on-black for my terminal).

funny that iterm2 which i used before can do everything including baked beans with bananas, except handling Unicode 32bit codepoints and... proper window handling.

**Comment by darwin** [comment]
2) Behaviour you are describing is by-design. It is technically impossible for TotalTerminal to do any modifications to Terminal behaviour BEFORE it gets injected in Terminal.app process. If you set `TotalTerminalCloseWindowsOnStart` to true, you are saying that you want TotalTerminal to close all windows when TotalTerminal starts (meaning when it gets injected into Terminal.app), but at that point Terminal.app might have done many things, for example restored previous windows configuration. That is why you are seeing windows getting open and then closed in quick but still visible sequence, because you launched Terminal.app and injected TotalTerminal few seconds later.

I don't follow your "letterbox windows" notes and don't know what do you mean by "a small-print black-on-white window".

If you want TotalTerminal not to open visor window after injection and not close existing windows after injection, please run these two tweaks:

```
defaults write com.apple.Terminal TotalTerminalDoNotOpenVisorDuringStartup -bool yes
defaults write com.apple.Terminal TotalTerminalCloseWindowsOnStart -bool no
```

**Comment by loveencounterflow** [comment]
ok so i did the exact settings, logged out and back in and they appear to work. thanks a lot!

with letterbox i mean what you call visor, i wasn't aware of that word. that one has a small font size and its style is pretty much the default OSX terminal windows style with black writing on a white background.

**Comment by darwin** [comment]
btw. You can tweak Visor terminal appearance in "Visor" profile under Terminal Preferences -> Profiles

**Comment by loveencounterflow** [comment]
oh i see. thanks for your help!
