### ISSUE TITLE
No longer able to access the TotalTerminal settings

### ISSUE THREAD

**Issue by milgrim** [binaryage/totalterminal#97]
I don't remember exactly what it's called and when it became available, but some time ago I enabled a new option that keeps the terminal application in the background when it's open. Since then I can no longer access the settings because I am no longer able to access the terminals menu bar. I tried to remove the ˜/Library/Preferences/ files for the terminal and totalterminal applications to reset everything but that did not work. 
Does anyone have any hints for me on how I can revert that setting?

**Comment by darwin** [comment]
I think @popavo could recall.

**Comment by WonderBeat** [comment]
Oh. Same problem. I've removed total terminal icon from app panel and now I can't open settings. Need help

**Comment by foxxyz** [comment]
This shortcut might help to access settings without the menu bar: `Cmd` + `,`

**Comment by milgrim** [comment]
Awesome, that did the trick. Thanks!

**Comment by darwin** [comment]
Yep. TotalTerminal settings are just one tab in Terminal.app settings. You can go through `Main Menu -> Terminal -> Preferences...` as well.

**Comment by milgrim** [comment]
What do you mean by "Main Menu"?

**Comment by darwin** [comment]
Each app displays main menu in top left corner of the main display. Look
for apple icon in the top-left corner :)

**Comment by milgrim** [comment]
Well, that was the main problem. By activating "Run Terminal.app as a background app" I was no longer able to access the main menu of terminal ;)

**Comment by darwin** [comment]
Ah, now I see. You are right. This is a problem.

**Comment by milgrim** [comment]
Yes. Maybe you could just make the background option only available after enabling the status menu icon for total terminal. But anyway: thanks for your help and a great application!

**Comment by BartoszKaszewczuk** [comment]
One workaround is to kill `TotalTerminalCrashWatcher`, `TotalTerminal` and `Terminal`; then restating `Terminal.app`, opening preferences window (`CMD` + `,`) and then starting `TotalTerminal`. 

This way you can open preferences window before `TotalTerminal` injects its code and after starting `TotalTerminal` a new tab with `TotalTerminal` preferences will appear allowing you to edit any settings.
Hope this helps.

**Comment by janstieler** [comment]
Thanks for your workaround.

**Comment by popavo** [comment]
@darwin A possible solution would be to enable the status item when "Run Terminal.app as a background app" is enabled. That way, there would always be a GUI method to open prefs.

**Comment by darwin** [comment]
Solved in 1.5.2:
http://totalterminal.binaryage.com/#1.5.2

Implemented @popavo's proposal. 

For individuals unhappy with this change, there is a new plist tweak:

```
defaults write com.apple.Terminal TotalTerminalHideStatusItemRegardless -bool yes
```

**Comment by nach0** [comment]
Wow, I came here to complain about having the menu bar icon always present with 1.5.4, just to see you had already offered a workaround for people like me. Thumbs up for you!

**Comment by mikeploeger** [comment]
Thanks for the workaround :+1: 
In my opinion, the option to disable the menubar entry of total terminal  if terminal is running as a background app should be available with a custom 'hint' or 'are you really sure' message.

Because the current solution leads to problems like:
I'am using the App 'Bartender', which has an option to hide menu bar elements, but total terminal is the only application (because of this changed made here) which can't get removed without knowing this workaround (defaults write com.apple.Terminal TotalTerminalHideStatusItemRegardless -bool yes).
I think every user, of this software should have this option in the pref pane.

Alternative:
Make a hint box in the pref panel with some kind of text:
'To hide total terminal in the menu bar type the following: defaults write com.apple.Terminal TotalTerminalHideStatusItemRegardless -bool yes'
